// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"net/http"
)

type CreateNotificationTemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Single notification template response
	NotificationTemplate *shared.NotificationTemplate
	// Client error
	Error *shared.Error
}

func (c *CreateNotificationTemplateResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateNotificationTemplateResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateNotificationTemplateResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateNotificationTemplateResponse) GetNotificationTemplate() *shared.NotificationTemplate {
	if c == nil {
		return nil
	}
	return c.NotificationTemplate
}

func (c *CreateNotificationTemplateResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
