// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"net/http"
)

type DeleteNotificationTemplateRequest struct {
	// Template ID (UUID)
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteNotificationTemplateRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteNotificationTemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Single notification template response
	NotificationTemplate *shared.NotificationTemplate
	// Unauthorized
	Error *shared.Error
}

func (d *DeleteNotificationTemplateResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteNotificationTemplateResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteNotificationTemplateResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteNotificationTemplateResponse) GetNotificationTemplate() *shared.NotificationTemplate {
	if d == nil {
		return nil
	}
	return d.NotificationTemplate
}

func (d *DeleteNotificationTemplateResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
