// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"net/http"
)

type GetNotificationsV2Request struct {
	// Base64 encoded cursor to be used for pagination
	Cursor  *string `queryParam:"style=form,explode=true,name=cursor"`
	AfterID *int64  `queryParam:"style=form,explode=true,name=after_id"`
	// The numbers of items to return
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
}

func (g *GetNotificationsV2Request) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}

func (g *GetNotificationsV2Request) GetAfterID() *int64 {
	if g == nil {
		return nil
	}
	return g.AfterID
}

func (g *GetNotificationsV2Request) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

// #region class-body-getnotificationsv2request
// #endregion class-body-getnotificationsv2request

// GetNotificationsV2ResponseBody - Success
type GetNotificationsV2ResponseBody struct {
	// Base64 encoded cursor to be used for pagination
	Cursor      *string                   `json:"cursor,omitempty"`
	Total       *int64                    `json:"total,omitempty"`
	TotalUnread *int64                    `json:"total_unread,omitempty"`
	Results     []shared.NotificationItem `json:"results,omitempty"`
}

func (g *GetNotificationsV2ResponseBody) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}

func (g *GetNotificationsV2ResponseBody) GetTotal() *int64 {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GetNotificationsV2ResponseBody) GetTotalUnread() *int64 {
	if g == nil {
		return nil
	}
	return g.TotalUnread
}

func (g *GetNotificationsV2ResponseBody) GetResults() []shared.NotificationItem {
	if g == nil {
		return nil
	}
	return g.Results
}

// #region class-body-getnotificationsv2responsebody
// #endregion class-body-getnotificationsv2responsebody

type GetNotificationsV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *GetNotificationsV2ResponseBody
}

func (g *GetNotificationsV2Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetNotificationsV2Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetNotificationsV2Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetNotificationsV2Response) GetObject() *GetNotificationsV2ResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

// #region class-body-getnotificationsv2response
// #endregion class-body-getnotificationsv2response
