// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"net/http"
)

type GetNotificationRequest struct {
	// Notification Id
	ID float64 `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetNotificationRequest) GetID() float64 {
	if g == nil {
		return 0.0
	}
	return g.ID
}

type GetNotificationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	NotificationItem *shared.NotificationItem
}

func (g *GetNotificationResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetNotificationResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetNotificationResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetNotificationResponse) GetNotificationItem() *shared.NotificationItem {
	if g == nil {
		return nil
	}
	return g.NotificationItem
}
