// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"net/http"
)

type GetNotificationsRequest struct {
	AfterID *int64 `queryParam:"style=form,explode=true,name=after_id"`
	// The numbers of items to return
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// When true, the payload will not be hydrated with the entity data. This is useful when the client does not need the entity data and wants to save on API calls (performance gain). When false, the payload will be hydrated with the entity data. This is useful when the client needs the entity data to display the notification (e.g. to show the name of the contact in the notification message), but can have a significative performance impact.
	//
	// This endpoint will eventually be deprecated in favor of GET /v2/notification/notifications which no longer hydrates the payload by default.
	//
	NoHydrate *bool `queryParam:"style=form,explode=true,name=no_hydrate"`
}

func (g *GetNotificationsRequest) GetAfterID() *int64 {
	if g == nil {
		return nil
	}
	return g.AfterID
}

func (g *GetNotificationsRequest) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetNotificationsRequest) GetNoHydrate() *bool {
	if g == nil {
		return nil
	}
	return g.NoHydrate
}

// GetNotificationsResponseBody - Success
type GetNotificationsResponseBody struct {
	Total       *int64                    `json:"total,omitempty"`
	TotalUnread *int64                    `json:"total_unread,omitempty"`
	Results     []shared.NotificationItem `json:"results,omitempty"`
}

func (g *GetNotificationsResponseBody) GetTotal() *int64 {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GetNotificationsResponseBody) GetTotalUnread() *int64 {
	if g == nil {
		return nil
	}
	return g.TotalUnread
}

func (g *GetNotificationsResponseBody) GetResults() []shared.NotificationItem {
	if g == nil {
		return nil
	}
	return g.Results
}

type GetNotificationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *GetNotificationsResponseBody
}

func (g *GetNotificationsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetNotificationsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetNotificationsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetNotificationsResponse) GetObject() *GetNotificationsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
