// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"net/http"
)

type GetNotificationTemplateRequest struct {
	// Template ID (UUID)
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetNotificationTemplateRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetNotificationTemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Single notification template response
	NotificationTemplate *shared.NotificationTemplate
	// Unauthorized
	Error *shared.Error
}

func (g *GetNotificationTemplateResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetNotificationTemplateResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetNotificationTemplateResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetNotificationTemplateResponse) GetNotificationTemplate() *shared.NotificationTemplate {
	if g == nil {
		return nil
	}
	return g.NotificationTemplate
}

func (g *GetNotificationTemplateResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
