// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"net/http"
)

type ListNotificationTemplatesRequest struct {
	// Lucene query string for filtering (default returns all)
	Q *string `queryParam:"style=form,explode=true,name=q"`
	// Pagination offset (0-based)
	From *int64 `default:"0" queryParam:"style=form,explode=true,name=from"`
	// Maximum number of results to return (max 1000)
	Size *int64 `default:"25" queryParam:"style=form,explode=true,name=size"`
	// Sort field(s), prefix with - for descending
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// Comma-separated list of fields to include
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
	// When true, resolves nested relation references
	Hydrate *bool `default:"false" queryParam:"style=form,explode=true,name=hydrate"`
}

func (l ListNotificationTemplatesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListNotificationTemplatesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListNotificationTemplatesRequest) GetQ() *string {
	if l == nil {
		return nil
	}
	return l.Q
}

func (l *ListNotificationTemplatesRequest) GetFrom() *int64 {
	if l == nil {
		return nil
	}
	return l.From
}

func (l *ListNotificationTemplatesRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

func (l *ListNotificationTemplatesRequest) GetSort() *string {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListNotificationTemplatesRequest) GetFields() *string {
	if l == nil {
		return nil
	}
	return l.Fields
}

func (l *ListNotificationTemplatesRequest) GetHydrate() *bool {
	if l == nil {
		return nil
	}
	return l.Hydrate
}

// ListNotificationTemplatesResponseBody - List of notification templates
type ListNotificationTemplatesResponseBody struct {
	Results []shared.NotificationTemplate `json:"results,omitempty"`
	// Total number of results
	Hits *int64 `json:"hits,omitempty"`
}

func (l *ListNotificationTemplatesResponseBody) GetResults() []shared.NotificationTemplate {
	if l == nil {
		return nil
	}
	return l.Results
}

func (l *ListNotificationTemplatesResponseBody) GetHits() *int64 {
	if l == nil {
		return nil
	}
	return l.Hits
}

type ListNotificationTemplatesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of notification templates
	Object *ListNotificationTemplatesResponseBody
	// Unauthorized
	Error *shared.Error
}

func (l *ListNotificationTemplatesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListNotificationTemplatesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListNotificationTemplatesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListNotificationTemplatesResponse) GetObject() *ListNotificationTemplatesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}

func (l *ListNotificationTemplatesResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
