// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type MarkAsReadRequest struct {
	// Numeric ID of the notification to mark as read
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (m *MarkAsReadRequest) GetID() int64 {
	if m == nil {
		return 0
	}
	return m.ID
}

type MarkAsReadResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (m *MarkAsReadResponse) GetContentType() string {
	if m == nil {
		return ""
	}
	return m.ContentType
}

func (m *MarkAsReadResponse) GetStatusCode() int {
	if m == nil {
		return 0
	}
	return m.StatusCode
}

func (m *MarkAsReadResponse) GetRawResponse() *http.Response {
	if m == nil {
		return nil
	}
	return m.RawResponse
}
