// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"net/http"
)

type PatchNotificationTemplateRequest struct {
	// Template ID (UUID)
	ID                              string                                 `pathParam:"style=simple,explode=false,name=id"`
	UpdateNotificationTemplateInput shared.UpdateNotificationTemplateInput `request:"mediaType=application/json"`
}

func (p *PatchNotificationTemplateRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PatchNotificationTemplateRequest) GetUpdateNotificationTemplateInput() shared.UpdateNotificationTemplateInput {
	if p == nil {
		return shared.UpdateNotificationTemplateInput{}
	}
	return p.UpdateNotificationTemplateInput
}

type PatchNotificationTemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	NotificationTemplate *shared.NotificationTemplate
	// Bad Request
	Error *shared.Error
}

func (p *PatchNotificationTemplateResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchNotificationTemplateResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchNotificationTemplateResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PatchNotificationTemplateResponse) GetNotificationTemplate() *shared.NotificationTemplate {
	if p == nil {
		return nil
	}
	return p.NotificationTemplate
}

func (p *PatchNotificationTemplateResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}
