// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"net/http"
)

type SendPreviewResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Preview notification sent successfully
	SendPreviewResponse []shared.SendPreviewResponse
	// Bad Request
	Error *shared.Error
}

func (s *SendPreviewResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SendPreviewResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SendPreviewResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SendPreviewResponse) GetSendPreviewResponse() []shared.SendPreviewResponse {
	if s == nil {
		return nil
	}
	return s.SendPreviewResponse
}

func (s *SendPreviewResponse) GetError() *shared.Error {
	if s == nil {
		return nil
	}
	return s.Error
}
