// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"net/http"
)

type UpdateNotificationTemplateRequest struct {
	// Template ID (UUID)
	ID                              string                                 `pathParam:"style=simple,explode=false,name=id"`
	UpdateNotificationTemplateInput shared.UpdateNotificationTemplateInput `request:"mediaType=application/json"`
}

func (u *UpdateNotificationTemplateRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateNotificationTemplateRequest) GetUpdateNotificationTemplateInput() shared.UpdateNotificationTemplateInput {
	if u == nil {
		return shared.UpdateNotificationTemplateInput{}
	}
	return u.UpdateNotificationTemplateInput
}

type UpdateNotificationTemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	NotificationTemplate *shared.NotificationTemplate
	// Bad Request
	Error *shared.Error
}

func (u *UpdateNotificationTemplateResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateNotificationTemplateResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateNotificationTemplateResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateNotificationTemplateResponse) GetNotificationTemplate() *shared.NotificationTemplate {
	if u == nil {
		return nil
	}
	return u.NotificationTemplate
}

func (u *UpdateNotificationTemplateResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
