// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CreateNotificationTemplateInput - Input for creating a new notification template
type CreateNotificationTemplateInput struct {
	// Template name
	Name string `json:"name"`
	// Template type identifier
	Type string `json:"type"`
	// Notification heading
	Heading *string `json:"heading,omitempty"`
	// Notification message content
	Message *string `json:"message,omitempty"`
	// Display title
	Title *string `json:"_title,omitempty"`
	// Tags for categorization
	Tags []string `json:"_tags,omitempty"`
}

func (c *CreateNotificationTemplateInput) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateNotificationTemplateInput) GetType() string {
	if c == nil {
		return ""
	}
	return c.Type
}

func (c *CreateNotificationTemplateInput) GetHeading() *string {
	if c == nil {
		return nil
	}
	return c.Heading
}

func (c *CreateNotificationTemplateInput) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *CreateNotificationTemplateInput) GetTitle() *string {
	if c == nil {
		return nil
	}
	return c.Title
}

func (c *CreateNotificationTemplateInput) GetTags() []string {
	if c == nil {
		return nil
	}
	return c.Tags
}
