// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateNotificationTemplateInput struct {
	// Internal template name (required)
	Name string `json:"name"`
	// Notification type key (required)
	Type string `json:"type"`
	// Notification title (Lexical editor JSON, supports variables)
	NotificationTitle *string `json:"notification_title,omitempty"`
	// Notification body (Lexical editor JSON, supports variables)
	Message *string `json:"message,omitempty"`
	// CTA button text (supports variables)
	ActionLabel *string `json:"action_label,omitempty"`
	// CTA button URL (supports variables)
	ActionURL *string `json:"action_url,omitempty"`
	// JSON string with style config
	Style *string `json:"style,omitempty"`
	// Display title
	Title *string `json:"_title,omitempty"`
	// Tags for categorization
	Tags []string `json:"_tags,omitempty"`
	// Manifest ID used to create/update the entity
	Manifest []string `json:"_manifest,omitempty"`
}

func (c *CreateNotificationTemplateInput) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateNotificationTemplateInput) GetType() string {
	if c == nil {
		return ""
	}
	return c.Type
}

func (c *CreateNotificationTemplateInput) GetNotificationTitle() *string {
	if c == nil {
		return nil
	}
	return c.NotificationTitle
}

func (c *CreateNotificationTemplateInput) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *CreateNotificationTemplateInput) GetActionLabel() *string {
	if c == nil {
		return nil
	}
	return c.ActionLabel
}

func (c *CreateNotificationTemplateInput) GetActionURL() *string {
	if c == nil {
		return nil
	}
	return c.ActionURL
}

func (c *CreateNotificationTemplateInput) GetStyle() *string {
	if c == nil {
		return nil
	}
	return c.Style
}

func (c *CreateNotificationTemplateInput) GetTitle() *string {
	if c == nil {
		return nil
	}
	return c.Title
}

func (c *CreateNotificationTemplateInput) GetTags() []string {
	if c == nil {
		return nil
	}
	return c.Tags
}

func (c *CreateNotificationTemplateInput) GetManifest() []string {
	if c == nil {
		return nil
	}
	return c.Manifest
}
