// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EntityOwner struct {
	// Organization ID
	OrgID *string `json:"org_id,omitempty"`
	// User ID
	UserID *string `json:"user_id,omitempty"`
}

func (e *EntityOwner) GetOrgID() *string {
	if e == nil {
		return nil
	}
	return e.OrgID
}

func (e *EntityOwner) GetUserID() *string {
	if e == nil {
		return nil
	}
	return e.UserID
}
