// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Params struct {
	ID *string `json:"id,omitempty"`
	// URL-friendly identifier for the entity schema
	Slug *string `json:"slug,omitempty"`
}

func (p *Params) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *Params) GetSlug() *string {
	if p == nil {
		return nil
	}
	return p.Slug
}

type EntityOperation struct {
	Entity    string         `json:"entity"`
	Operation *string        `json:"operation,omitempty"`
	Params    *Params        `json:"params,omitempty"`
	Payload   map[string]any `json:"payload,omitempty"`
}

func (e *EntityOperation) GetEntity() string {
	if e == nil {
		return ""
	}
	return e.Entity
}

func (e *EntityOperation) GetOperation() *string {
	if e == nil {
		return nil
	}
	return e.Operation
}

func (e *EntityOperation) GetParams() *Params {
	if e == nil {
		return nil
	}
	return e.Params
}

func (e *EntityOperation) GetPayload() map[string]any {
	if e == nil {
		return nil
	}
	return e.Payload
}
