// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Error - Unauthorized
type Error struct {
	// HTTP status code
	Status *int64 `json:"status,omitempty"`
	// Error message
	Error *string `json:"error,omitempty"`
}

func (e *Error) GetStatus() *int64 {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *Error) GetError() *string {
	if e == nil {
		return nil
	}
	return e.Error
}
