// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Error struct {
	// Error message
	Message string `json:"message"`
	// Error code
	Code *string `json:"code,omitempty"`
}

func (e *Error) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *Error) GetCode() *string {
	if e == nil {
		return nil
	}
	return e.Code
}
