// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/internal/utils"
)

type Token struct {
	Sub             *string `json:"sub,omitempty"`
	Email           *string `json:"email,omitempty"`
	CognitoUsername *string `json:"cognito:username,omitempty"`
	CustomIvyUserID *string `json:"custom:ivy_user_id,omitempty"`
}

func (t *Token) GetSub() *string {
	if t == nil {
		return nil
	}
	return t.Sub
}

func (t *Token) GetEmail() *string {
	if t == nil {
		return nil
	}
	return t.Email
}

func (t *Token) GetCognitoUsername() *string {
	if t == nil {
		return nil
	}
	return t.CognitoUsername
}

func (t *Token) GetCustomIvyUserID() *string {
	if t == nil {
		return nil
	}
	return t.CustomIvyUserID
}

type EpilotAuth struct {
	Token *Token `json:"token,omitempty"`
}

func (e *EpilotAuth) GetToken() *Token {
	if e == nil {
		return nil
	}
	return e.Token
}

type NotificationCallerContext struct {
	EpilotAuth           *EpilotAuth `json:"EpilotAuth,omitempty"`
	AdditionalProperties any         `additionalProperties:"true" json:"-"`
}

func (n NotificationCallerContext) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NotificationCallerContext) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NotificationCallerContext) GetEpilotAuth() *EpilotAuth {
	if n == nil {
		return nil
	}
	return n.EpilotAuth
}

func (n *NotificationCallerContext) GetAdditionalProperties() any {
	if n == nil {
		return nil
	}
	return n.AdditionalProperties
}
