// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/internal/utils"
	"time"
)

type Title struct {
	// Title for notification. Supports handlebars syntax.
	En *string `json:"en,omitempty"`
	// Title for notification. Supports handlebars syntax.
	De *string `json:"de,omitempty"`
}

func (t *Title) GetEn() *string {
	if t == nil {
		return nil
	}
	return t.En
}

func (t *Title) GetDe() *string {
	if t == nil {
		return nil
	}
	return t.De
}

type Message struct {
	// Message for notification. Supports handlebars syntax.
	En *string `json:"en,omitempty"`
	// Message for notification. Supports handlebars syntax.
	De *string `json:"de,omitempty"`
}

func (m *Message) GetEn() *string {
	if m == nil {
		return nil
	}
	return m.En
}

func (m *Message) GetDe() *string {
	if m == nil {
		return nil
	}
	return m.De
}

type NotificationItem struct {
	ID             *float64   `json:"id,omitempty"`
	NotificationID *float64   `json:"notification_id,omitempty"`
	Timestamp      *time.Time `json:"timestamp,omitempty"`
	ReadState      *bool      `json:"read_state,omitempty"`
	// Type of notification
	Type string `json:"type"`
	// Redirect url
	RedirectURL *string `json:"redirect_url,omitempty"`
	// Organization Id
	OrganizationID   *string                    `json:"organization_id,omitempty"`
	Title            Title                      `json:"title"`
	Message          Message                    `json:"message"`
	Payload          map[string]any             `json:"payload,omitempty"`
	Caller           *NotificationCallerContext `json:"caller,omitempty"`
	Operations       []EntityOperation          `json:"operations,omitempty"`
	ForceNotifyUsers map[string]any             `json:"force_notify_users,omitempty"`
}

func (n NotificationItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NotificationItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NotificationItem) GetID() *float64 {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NotificationItem) GetNotificationID() *float64 {
	if n == nil {
		return nil
	}
	return n.NotificationID
}

func (n *NotificationItem) GetTimestamp() *time.Time {
	if n == nil {
		return nil
	}
	return n.Timestamp
}

func (n *NotificationItem) GetReadState() *bool {
	if n == nil {
		return nil
	}
	return n.ReadState
}

func (n *NotificationItem) GetType() string {
	if n == nil {
		return ""
	}
	return n.Type
}

func (n *NotificationItem) GetRedirectURL() *string {
	if n == nil {
		return nil
	}
	return n.RedirectURL
}

func (n *NotificationItem) GetOrganizationID() *string {
	if n == nil {
		return nil
	}
	return n.OrganizationID
}

func (n *NotificationItem) GetTitle() Title {
	if n == nil {
		return Title{}
	}
	return n.Title
}

func (n *NotificationItem) GetMessage() Message {
	if n == nil {
		return Message{}
	}
	return n.Message
}

func (n *NotificationItem) GetPayload() map[string]any {
	if n == nil {
		return nil
	}
	return n.Payload
}

func (n *NotificationItem) GetCaller() *NotificationCallerContext {
	if n == nil {
		return nil
	}
	return n.Caller
}

func (n *NotificationItem) GetOperations() []EntityOperation {
	if n == nil {
		return nil
	}
	return n.Operations
}

func (n *NotificationItem) GetForceNotifyUsers() map[string]any {
	if n == nil {
		return nil
	}
	return n.ForceNotifyUsers
}
