// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NotificationTemplateListResponse struct {
	Results []NotificationTemplate `json:"results,omitempty"`
	// Total number of matching results
	Hits *int64 `json:"hits,omitempty"`
}

func (n *NotificationTemplateListResponse) GetResults() []NotificationTemplate {
	if n == nil {
		return nil
	}
	return n.Results
}

func (n *NotificationTemplateListResponse) GetHits() *int64 {
	if n == nil {
		return nil
	}
	return n.Hits
}
