// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/internal/utils"
	"time"
)

type NotificationTitle struct {
	// Title for notification. Supports handlebars syntax.
	En *string `json:"en,omitempty"`
	// Title for notification. Supports handlebars syntax.
	De *string `json:"de,omitempty"`
}

func (n *NotificationTitle) GetEn() *string {
	if n == nil {
		return nil
	}
	return n.En
}

func (n *NotificationTitle) GetDe() *string {
	if n == nil {
		return nil
	}
	return n.De
}

type NotificationMessage struct {
	// Message for notification. Supports handlebars syntax.
	En *string `json:"en,omitempty"`
	// Message for notification. Supports handlebars syntax.
	De *string `json:"de,omitempty"`
}

func (n *NotificationMessage) GetEn() *string {
	if n == nil {
		return nil
	}
	return n.En
}

func (n *NotificationMessage) GetDe() *string {
	if n == nil {
		return nil
	}
	return n.De
}

type Notification struct {
	NotificationID *float64   `json:"notification_id,omitempty"`
	Timestamp      *time.Time `json:"timestamp,omitempty"`
	// Type of notification
	Type string `json:"type"`
	// Redirect url
	RedirectURL *string `json:"redirect_url,omitempty"`
	// Organization Id
	OrganizationID   *string                    `json:"organization_id,omitempty"`
	Title            NotificationTitle          `json:"title"`
	Message          NotificationMessage        `json:"message"`
	Payload          map[string]any             `json:"payload,omitempty"`
	Caller           *NotificationCallerContext `json:"caller,omitempty"`
	Operations       []EntityOperation          `json:"operations,omitempty"`
	ForceNotifyUsers map[string]any             `json:"force_notify_users,omitempty"`
	ReadState        *bool                      `json:"read_state,omitempty"`
	// The person who is the corresponding event recipient.
	VisibilityUserIds []string `json:"visibility_user_ids,omitempty"`
}

func (n Notification) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *Notification) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *Notification) GetNotificationID() *float64 {
	if n == nil {
		return nil
	}
	return n.NotificationID
}

func (n *Notification) GetTimestamp() *time.Time {
	if n == nil {
		return nil
	}
	return n.Timestamp
}

func (n *Notification) GetType() string {
	if n == nil {
		return ""
	}
	return n.Type
}

func (n *Notification) GetRedirectURL() *string {
	if n == nil {
		return nil
	}
	return n.RedirectURL
}

func (n *Notification) GetOrganizationID() *string {
	if n == nil {
		return nil
	}
	return n.OrganizationID
}

func (n *Notification) GetTitle() NotificationTitle {
	if n == nil {
		return NotificationTitle{}
	}
	return n.Title
}

func (n *Notification) GetMessage() NotificationMessage {
	if n == nil {
		return NotificationMessage{}
	}
	return n.Message
}

func (n *Notification) GetPayload() map[string]any {
	if n == nil {
		return nil
	}
	return n.Payload
}

func (n *Notification) GetCaller() *NotificationCallerContext {
	if n == nil {
		return nil
	}
	return n.Caller
}

func (n *Notification) GetOperations() []EntityOperation {
	if n == nil {
		return nil
	}
	return n.Operations
}

func (n *Notification) GetForceNotifyUsers() map[string]any {
	if n == nil {
		return nil
	}
	return n.ForceNotifyUsers
}

func (n *Notification) GetReadState() *bool {
	if n == nil {
		return nil
	}
	return n.ReadState
}

func (n *Notification) GetVisibilityUserIds() []string {
	if n == nil {
		return nil
	}
	return n.VisibilityUserIds
}
