// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/internal/utils"
	"time"
)

// NotificationTemplate - A notification template entity
type NotificationTemplate struct {
	// Unique identifier
	ID string `json:"_id"`
	// Entity schema type
	Schema *string `json:"_schema,omitempty"`
	// Display title
	Title *string `json:"_title,omitempty"`
	// Organization ID
	Org *string `json:"_org,omitempty"`
	// Tags for categorization
	Tags []string `json:"_tags,omitempty"`
	// ISO timestamp of creation
	CreatedAt *time.Time `json:"_created_at,omitempty"`
	// ISO timestamp of last update
	UpdatedAt *time.Time `json:"_updated_at,omitempty"`
	// Template name
	Name string `json:"name"`
	// Template type identifier
	Type string `json:"type"`
	// Notification heading
	Heading *string `json:"heading,omitempty"`
	// Notification message content
	Message *string `json:"message,omitempty"`
}

func (n NotificationTemplate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NotificationTemplate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NotificationTemplate) GetID() string {
	if n == nil {
		return ""
	}
	return n.ID
}

func (n *NotificationTemplate) GetSchema() *string {
	if n == nil {
		return nil
	}
	return n.Schema
}

func (n *NotificationTemplate) GetTitle() *string {
	if n == nil {
		return nil
	}
	return n.Title
}

func (n *NotificationTemplate) GetOrg() *string {
	if n == nil {
		return nil
	}
	return n.Org
}

func (n *NotificationTemplate) GetTags() []string {
	if n == nil {
		return nil
	}
	return n.Tags
}

func (n *NotificationTemplate) GetCreatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.CreatedAt
}

func (n *NotificationTemplate) GetUpdatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.UpdatedAt
}

func (n *NotificationTemplate) GetName() string {
	if n == nil {
		return ""
	}
	return n.Name
}

func (n *NotificationTemplate) GetType() string {
	if n == nil {
		return ""
	}
	return n.Type
}

func (n *NotificationTemplate) GetHeading() *string {
	if n == nil {
		return nil
	}
	return n.Heading
}

func (n *NotificationTemplate) GetMessage() *string {
	if n == nil {
		return nil
	}
	return n.Message
}
