// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SendPreviewResponse struct {
	// Whether this notification was sent successfully
	Success bool `json:"success"`
	// Result data
	Data any `json:"data,omitempty"`
}

func (s *SendPreviewResponse) GetSuccess() bool {
	if s == nil {
		return false
	}
	return s.Success
}

func (s *SendPreviewResponse) GetData() any {
	if s == nil {
		return nil
	}
	return s.Data
}
