// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SendPreviewInput struct {
	Template UpdateNotificationTemplateInput `json:"template"`
	// Optional context IDs for variable replacement
	ContextIds map[string]string `json:"context_ids,omitempty"`
}

func (s *SendPreviewInput) GetTemplate() UpdateNotificationTemplateInput {
	if s == nil {
		return UpdateNotificationTemplateInput{}
	}
	return s.Template
}

func (s *SendPreviewInput) GetContextIds() map[string]string {
	if s == nil {
		return nil
	}
	return s.ContextIds
}
