// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateNotificationTemplateInput struct {
	// Internal template name
	Name *string `json:"name,omitempty"`
	// Notification title (Lexical editor JSON, supports variables)
	NotificationTitle *string `json:"notification_title,omitempty"`
	// Notification body (Lexical editor JSON, supports variables)
	Message *string `json:"message,omitempty"`
	// CTA button text (supports variables)
	ActionLabel *string `json:"action_label,omitempty"`
	// CTA button URL (supports variables)
	ActionURL *string `json:"action_url,omitempty"`
	// JSON string with style config
	Style *string `json:"style,omitempty"`
	// Display title
	Title *string `json:"_title,omitempty"`
	// Tags for categorization
	Tags []string `json:"_tags,omitempty"`
}

func (u *UpdateNotificationTemplateInput) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateNotificationTemplateInput) GetNotificationTitle() *string {
	if u == nil {
		return nil
	}
	return u.NotificationTitle
}

func (u *UpdateNotificationTemplateInput) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

func (u *UpdateNotificationTemplateInput) GetActionLabel() *string {
	if u == nil {
		return nil
	}
	return u.ActionLabel
}

func (u *UpdateNotificationTemplateInput) GetActionURL() *string {
	if u == nil {
		return nil
	}
	return u.ActionURL
}

func (u *UpdateNotificationTemplateInput) GetStyle() *string {
	if u == nil {
		return nil
	}
	return u.Style
}

func (u *UpdateNotificationTemplateInput) GetTitle() *string {
	if u == nil {
		return nil
	}
	return u.Title
}

func (u *UpdateNotificationTemplateInput) GetTags() []string {
	if u == nil {
		return nil
	}
	return u.Tags
}
