// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// UpdateNotificationTemplateInput - Input for updating an existing notification template
type UpdateNotificationTemplateInput struct {
	// Template name
	Name *string `json:"name,omitempty"`
	// Template type identifier
	Type *string `json:"type,omitempty"`
	// Notification heading
	Heading *string `json:"heading,omitempty"`
	// Notification message content
	Message *string `json:"message,omitempty"`
	// Display title
	Title *string `json:"_title,omitempty"`
	// Tags for categorization
	Tags []string `json:"_tags,omitempty"`
}

func (u *UpdateNotificationTemplateInput) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateNotificationTemplateInput) GetType() *string {
	if u == nil {
		return nil
	}
	return u.Type
}

func (u *UpdateNotificationTemplateInput) GetHeading() *string {
	if u == nil {
		return nil
	}
	return u.Heading
}

func (u *UpdateNotificationTemplateInput) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

func (u *UpdateNotificationTemplateInput) GetTitle() *string {
	if u == nil {
		return nil
	}
	return u.Title
}

func (u *UpdateNotificationTemplateInput) GetTags() []string {
	if u == nil {
		return nil
	}
	return u.Tags
}
