// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &NotificationTemplateDataSource{}
var _ datasource.DataSourceWithConfigure = &NotificationTemplateDataSource{}

func NewNotificationTemplateDataSource() datasource.DataSource {
	return &NotificationTemplateDataSource{}
}

// NotificationTemplateDataSource is the data source implementation.
type NotificationTemplateDataSource struct {
	// Provider configured SDK client.
	client *sdk.SDK
}

// NotificationTemplateDataSourceModel describes the data model.
type NotificationTemplateDataSourceModel struct {
	ACL               *tfTypes.ACL          `tfsdk:"acl"`
	ActionLabel       types.String          `tfsdk:"action_label"`
	ActionURL         types.String          `tfsdk:"action_url"`
	CreatedAt         types.String          `tfsdk:"created_at"`
	CreatedBy         types.String          `tfsdk:"created_by"`
	ID                types.String          `tfsdk:"id"`
	Manifest          []types.String        `tfsdk:"manifest"`
	Message           types.String          `tfsdk:"message"`
	Name              types.String          `tfsdk:"name"`
	NotificationTitle types.String          `tfsdk:"notification_title"`
	Org               types.String          `tfsdk:"org"`
	Owners            []tfTypes.EntityOwner `tfsdk:"owners"`
	Schema            types.String          `tfsdk:"schema"`
	Style             types.String          `tfsdk:"style"`
	SystemTemplate    types.Bool            `tfsdk:"system_template"`
	Tags              []types.String        `tfsdk:"tags"`
	Title             types.String          `tfsdk:"title"`
	Type              types.String          `tfsdk:"type"`
	UpdatedAt         types.String          `tfsdk:"updated_at"`
	UpdatedBy         types.String          `tfsdk:"updated_by"`
}

// Metadata returns the data source type name.
func (r *NotificationTemplateDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_notification_template"
}

// Schema defines the schema for the data source.
func (r *NotificationTemplateDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "NotificationTemplate DataSource",

		Attributes: map[string]schema.Attribute{
			"acl": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"delete": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"edit": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"view": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
				},
				Description: `Access control list`,
			},
			"action_label": schema.StringAttribute{
				Computed:    true,
				Description: `CTA button text (supports variables)`,
			},
			"action_url": schema.StringAttribute{
				Computed:    true,
				Description: `CTA button URL (supports variables)`,
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: `ISO timestamp of creation`,
			},
			"created_by": schema.StringAttribute{
				Computed:    true,
				Description: `User ID who created the template`,
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `Unique identifier`,
			},
			"manifest": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `Manifest ID used to create/update the entity`,
			},
			"message": schema.StringAttribute{
				Computed:    true,
				Description: `Notification body (Lexical editor JSON, supports variables)`,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `Internal template name`,
			},
			"notification_title": schema.StringAttribute{
				Computed:    true,
				Description: `Notification title (Lexical editor JSON, supports variables)`,
			},
			"org": schema.StringAttribute{
				Computed:    true,
				Description: `Organization ID`,
			},
			"owners": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"org_id": schema.StringAttribute{
							Computed:    true,
							Description: `Organization ID`,
						},
						"user_id": schema.StringAttribute{
							Computed:    true,
							Description: `User ID`,
						},
					},
				},
				Description: `Entity owners`,
			},
			"schema": schema.StringAttribute{
				Computed:    true,
				Description: `Entity schema type`,
			},
			"style": schema.StringAttribute{
				Computed:    true,
				Description: `JSON string with style config`,
			},
			"system_template": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether this is a system template`,
			},
			"tags": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `Tags for categorization`,
			},
			"title": schema.StringAttribute{
				Computed:    true,
				Description: `Display title`,
			},
			"type": schema.StringAttribute{
				Computed:    true,
				Description: `Notification type key`,
			},
			"updated_at": schema.StringAttribute{
				Computed:    true,
				Description: `ISO timestamp of last update`,
			},
			"updated_by": schema.StringAttribute{
				Computed:    true,
				Description: `User ID who last updated the template`,
			},
		},
	}
}

func (r *NotificationTemplateDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *NotificationTemplateDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *NotificationTemplateDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetNotificationTemplateRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Template.GetNotificationTemplate(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.NotificationTemplate != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedNotificationTemplate(ctx, res.NotificationTemplate)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
