// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/provider/typeconvert"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *NotificationTemplateResourceModel) RefreshFromSharedNotificationTemplate(ctx context.Context, resp *shared.NotificationTemplate) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.ID = types.StringValue(resp.ID)
		r.Org = types.StringPointerValue(resp.Org)
		r.Schema = types.StringPointerValue(resp.Schema)
		r.Tags = make([]types.String, 0, len(resp.Tags))
		for _, v := range resp.Tags {
			r.Tags = append(r.Tags, types.StringValue(v))
		}
		r.Title = types.StringPointerValue(resp.Title)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
		r.Heading = types.StringPointerValue(resp.Heading)
		r.Message = types.StringPointerValue(resp.Message)
		r.Name = types.StringValue(resp.Name)
		r.Type = types.StringValue(resp.Type)
	}

	return diags
}

func (r *NotificationTemplateResourceModel) ToOperationsDeleteNotificationTemplateRequest(ctx context.Context) (*operations.DeleteNotificationTemplateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.DeleteNotificationTemplateRequest{
		ID: id,
	}

	return &out, diags
}

func (r *NotificationTemplateResourceModel) ToOperationsGetNotificationTemplateRequest(ctx context.Context) (*operations.GetNotificationTemplateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetNotificationTemplateRequest{
		ID: id,
	}

	return &out, diags
}

func (r *NotificationTemplateResourceModel) ToOperationsUpdateNotificationTemplateRequest(ctx context.Context) (*operations.UpdateNotificationTemplateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	updateNotificationTemplateInput, updateNotificationTemplateInputDiags := r.ToSharedUpdateNotificationTemplateInput(ctx)
	diags.Append(updateNotificationTemplateInputDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateNotificationTemplateRequest{
		ID:                              id,
		UpdateNotificationTemplateInput: *updateNotificationTemplateInput,
	}

	return &out, diags
}

func (r *NotificationTemplateResourceModel) ToSharedCreateNotificationTemplateInput(ctx context.Context) (*shared.CreateNotificationTemplateInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	var typeVar string
	typeVar = r.Type.ValueString()

	heading := new(string)
	if !r.Heading.IsUnknown() && !r.Heading.IsNull() {
		*heading = r.Heading.ValueString()
	} else {
		heading = nil
	}
	message := new(string)
	if !r.Message.IsUnknown() && !r.Message.IsNull() {
		*message = r.Message.ValueString()
	} else {
		message = nil
	}
	title := new(string)
	if !r.Title.IsUnknown() && !r.Title.IsNull() {
		*title = r.Title.ValueString()
	} else {
		title = nil
	}
	tags := make([]string, 0, len(r.Tags))
	for tagsIndex := range r.Tags {
		tags = append(tags, r.Tags[tagsIndex].ValueString())
	}
	out := shared.CreateNotificationTemplateInput{
		Name:    name,
		Type:    typeVar,
		Heading: heading,
		Message: message,
		Title:   title,
		Tags:    tags,
	}

	return &out, diags
}

func (r *NotificationTemplateResourceModel) ToSharedUpdateNotificationTemplateInput(ctx context.Context) (*shared.UpdateNotificationTemplateInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	typeVar := new(string)
	if !r.Type.IsUnknown() && !r.Type.IsNull() {
		*typeVar = r.Type.ValueString()
	} else {
		typeVar = nil
	}
	heading := new(string)
	if !r.Heading.IsUnknown() && !r.Heading.IsNull() {
		*heading = r.Heading.ValueString()
	} else {
		heading = nil
	}
	message := new(string)
	if !r.Message.IsUnknown() && !r.Message.IsNull() {
		*message = r.Message.ValueString()
	} else {
		message = nil
	}
	title := new(string)
	if !r.Title.IsUnknown() && !r.Title.IsNull() {
		*title = r.Title.ValueString()
	} else {
		title = nil
	}
	tags := make([]string, 0, len(r.Tags))
	for tagsIndex := range r.Tags {
		tags = append(tags, r.Tags[tagsIndex].ValueString())
	}
	out := shared.UpdateNotificationTemplateInput{
		Name:    name,
		Type:    typeVar,
		Heading: heading,
		Message: message,
		Title:   title,
		Tags:    tags,
	}

	return &out, diags
}
