// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/provider/typeconvert"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *NotificationTemplateResourceModel) RefreshFromSharedNotificationTemplate(ctx context.Context, resp *shared.NotificationTemplate) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.ACL == nil {
			r.ACL = nil
		} else {
			r.ACL = &tfTypes.ACL{}
			r.ACL.Delete = make([]types.String, 0, len(resp.ACL.Delete))
			for _, v := range resp.ACL.Delete {
				r.ACL.Delete = append(r.ACL.Delete, types.StringValue(v))
			}
			r.ACL.Edit = make([]types.String, 0, len(resp.ACL.Edit))
			for _, v := range resp.ACL.Edit {
				r.ACL.Edit = append(r.ACL.Edit, types.StringValue(v))
			}
			r.ACL.View = make([]types.String, 0, len(resp.ACL.View))
			for _, v := range resp.ACL.View {
				r.ACL.View = append(r.ACL.View, types.StringValue(v))
			}
		}
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.ID = types.StringValue(resp.ID)
		r.Org = types.StringValue(resp.Org)
		r.Owners = []tfTypes.EntityOwner{}

		for _, ownersItem := range resp.Owners {
			var owners tfTypes.EntityOwner

			owners.OrgID = types.StringValue(ownersItem.OrgID)
			owners.UserID = types.StringValue(ownersItem.UserID)

			r.Owners = append(r.Owners, owners)
		}
		r.Schema = types.StringValue(resp.Schema)
		r.Tags = make([]types.String, 0, len(resp.Tags))
		for _, v := range resp.Tags {
			r.Tags = append(r.Tags, types.StringValue(v))
		}
		r.Title = types.StringPointerValue(resp.Title)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
		r.ActionLabel = types.StringPointerValue(resp.ActionLabel)
		r.ActionURL = types.StringPointerValue(resp.ActionURL)
		r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
		r.Message = types.StringPointerValue(resp.Message)
		r.Name = types.StringPointerValue(resp.Name)
		r.NotificationTitle = types.StringPointerValue(resp.NotificationTitle)
		r.Style = types.StringPointerValue(resp.Style)
		r.SystemTemplate = types.BoolPointerValue(resp.SystemTemplate)
		r.Type = types.StringPointerValue(resp.Type)
		r.UpdatedBy = types.StringPointerValue(resp.UpdatedBy)
	}

	return diags
}

func (r *NotificationTemplateResourceModel) ToOperationsDeleteNotificationTemplateRequest(ctx context.Context) (*operations.DeleteNotificationTemplateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.DeleteNotificationTemplateRequest{
		ID: id,
	}

	return &out, diags
}

func (r *NotificationTemplateResourceModel) ToOperationsGetNotificationTemplateRequest(ctx context.Context) (*operations.GetNotificationTemplateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetNotificationTemplateRequest{
		ID: id,
	}

	return &out, diags
}

func (r *NotificationTemplateResourceModel) ToOperationsUpdateNotificationTemplateRequest(ctx context.Context) (*operations.UpdateNotificationTemplateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	updateNotificationTemplateInput, updateNotificationTemplateInputDiags := r.ToSharedUpdateNotificationTemplateInput(ctx)
	diags.Append(updateNotificationTemplateInputDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateNotificationTemplateRequest{
		ID:                              id,
		UpdateNotificationTemplateInput: *updateNotificationTemplateInput,
	}

	return &out, diags
}

func (r *NotificationTemplateResourceModel) ToSharedCreateNotificationTemplateInput(ctx context.Context) (*shared.CreateNotificationTemplateInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	var typeVar string
	typeVar = r.Type.ValueString()

	notificationTitle := new(string)
	if !r.NotificationTitle.IsUnknown() && !r.NotificationTitle.IsNull() {
		*notificationTitle = r.NotificationTitle.ValueString()
	} else {
		notificationTitle = nil
	}
	message := new(string)
	if !r.Message.IsUnknown() && !r.Message.IsNull() {
		*message = r.Message.ValueString()
	} else {
		message = nil
	}
	actionLabel := new(string)
	if !r.ActionLabel.IsUnknown() && !r.ActionLabel.IsNull() {
		*actionLabel = r.ActionLabel.ValueString()
	} else {
		actionLabel = nil
	}
	actionURL := new(string)
	if !r.ActionURL.IsUnknown() && !r.ActionURL.IsNull() {
		*actionURL = r.ActionURL.ValueString()
	} else {
		actionURL = nil
	}
	style := new(string)
	if !r.Style.IsUnknown() && !r.Style.IsNull() {
		*style = r.Style.ValueString()
	} else {
		style = nil
	}
	title := new(string)
	if !r.Title.IsUnknown() && !r.Title.IsNull() {
		*title = r.Title.ValueString()
	} else {
		title = nil
	}
	tags := make([]string, 0, len(r.Tags))
	for tagsIndex := range r.Tags {
		tags = append(tags, r.Tags[tagsIndex].ValueString())
	}
	out := shared.CreateNotificationTemplateInput{
		Name:              name,
		Type:              typeVar,
		NotificationTitle: notificationTitle,
		Message:           message,
		ActionLabel:       actionLabel,
		ActionURL:         actionURL,
		Style:             style,
		Title:             title,
		Tags:              tags,
	}

	return &out, diags
}

func (r *NotificationTemplateResourceModel) ToSharedUpdateNotificationTemplateInput(ctx context.Context) (*shared.UpdateNotificationTemplateInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	notificationTitle := new(string)
	if !r.NotificationTitle.IsUnknown() && !r.NotificationTitle.IsNull() {
		*notificationTitle = r.NotificationTitle.ValueString()
	} else {
		notificationTitle = nil
	}
	message := new(string)
	if !r.Message.IsUnknown() && !r.Message.IsNull() {
		*message = r.Message.ValueString()
	} else {
		message = nil
	}
	actionLabel := new(string)
	if !r.ActionLabel.IsUnknown() && !r.ActionLabel.IsNull() {
		*actionLabel = r.ActionLabel.ValueString()
	} else {
		actionLabel = nil
	}
	actionURL := new(string)
	if !r.ActionURL.IsUnknown() && !r.ActionURL.IsNull() {
		*actionURL = r.ActionURL.ValueString()
	} else {
		actionURL = nil
	}
	style := new(string)
	if !r.Style.IsUnknown() && !r.Style.IsNull() {
		*style = r.Style.ValueString()
	} else {
		style = nil
	}
	title := new(string)
	if !r.Title.IsUnknown() && !r.Title.IsNull() {
		*title = r.Title.ValueString()
	} else {
		title = nil
	}
	tags := make([]string, 0, len(r.Tags))
	for tagsIndex := range r.Tags {
		tags = append(tags, r.Tags[tagsIndex].ValueString())
	}
	out := shared.UpdateNotificationTemplateInput{
		Name:              name,
		NotificationTitle: notificationTitle,
		Message:           message,
		ActionLabel:       actionLabel,
		ActionURL:         actionURL,
		Style:             style,
		Title:             title,
		Tags:              tags,
	}

	return &out, diags
}
