// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/provider/typeconvert"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *NotificationTemplateDataSourceModel) RefreshFromSharedNotificationTemplate(ctx context.Context, resp *shared.NotificationTemplate) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.ID = types.StringValue(resp.ID)
		r.Org = types.StringPointerValue(resp.Org)
		r.Schema = types.StringPointerValue(resp.Schema)
		r.Tags = make([]types.String, 0, len(resp.Tags))
		for _, v := range resp.Tags {
			r.Tags = append(r.Tags, types.StringValue(v))
		}
		r.Title = types.StringPointerValue(resp.Title)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
		r.Heading = types.StringPointerValue(resp.Heading)
		r.Message = types.StringPointerValue(resp.Message)
		r.Name = types.StringValue(resp.Name)
		r.Type = types.StringValue(resp.Type)
	}

	return diags
}

func (r *NotificationTemplateDataSourceModel) ToOperationsGetNotificationTemplateRequest(ctx context.Context) (*operations.GetNotificationTemplateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetNotificationTemplateRequest{
		ID: id,
	}

	return &out, diags
}
