// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/provider/typeconvert"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-notificationtemplate/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *NotificationTemplateDataSourceModel) RefreshFromSharedNotificationTemplate(ctx context.Context, resp *shared.NotificationTemplate) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.ACL == nil {
			r.ACL = nil
		} else {
			r.ACL = &tfTypes.ACL{}
			r.ACL.Delete = make([]types.String, 0, len(resp.ACL.Delete))
			for _, v := range resp.ACL.Delete {
				r.ACL.Delete = append(r.ACL.Delete, types.StringValue(v))
			}
			r.ACL.Edit = make([]types.String, 0, len(resp.ACL.Edit))
			for _, v := range resp.ACL.Edit {
				r.ACL.Edit = append(r.ACL.Edit, types.StringValue(v))
			}
			r.ACL.View = make([]types.String, 0, len(resp.ACL.View))
			for _, v := range resp.ACL.View {
				r.ACL.View = append(r.ACL.View, types.StringValue(v))
			}
		}
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.ID = types.StringValue(resp.ID)
		r.Manifest = make([]types.String, 0, len(resp.Manifest))
		for _, v := range resp.Manifest {
			r.Manifest = append(r.Manifest, types.StringValue(v))
		}
		r.Org = types.StringValue(resp.Org)
		r.Owners = []tfTypes.EntityOwner{}

		for _, ownersItem := range resp.Owners {
			var owners tfTypes.EntityOwner

			owners.OrgID = types.StringValue(ownersItem.OrgID)
			owners.UserID = types.StringValue(ownersItem.UserID)

			r.Owners = append(r.Owners, owners)
		}
		r.Schema = types.StringValue(resp.Schema)
		if resp.Tags != nil {
			r.Tags = make([]types.String, 0, len(resp.Tags))
			for _, v := range resp.Tags {
				r.Tags = append(r.Tags, types.StringValue(v))
			}
		} else {
			r.Tags = nil
		}
		r.Title = types.StringPointerValue(resp.Title)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
		r.ActionLabel = types.StringPointerValue(resp.ActionLabel)
		r.ActionURL = types.StringPointerValue(resp.ActionURL)
		r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
		r.Message = types.StringPointerValue(resp.Message)
		r.Name = types.StringPointerValue(resp.Name)
		r.NotificationTitle = types.StringPointerValue(resp.NotificationTitle)
		r.Style = types.StringPointerValue(resp.Style)
		r.SystemTemplate = types.BoolPointerValue(resp.SystemTemplate)
		r.Type = types.StringPointerValue(resp.Type)
		r.UpdatedBy = types.StringPointerValue(resp.UpdatedBy)
	}

	return diags
}

func (r *NotificationTemplateDataSourceModel) ToOperationsGetNotificationTemplateRequest(ctx context.Context) (*operations.GetNotificationTemplateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetNotificationTemplateRequest{
		ID: id,
	}

	return &out, diags
}
